name: flutter_book_riverpod
description: "flutter book riverpod"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  flutter_slidable: ^4.0.0
  intl: ^0.19.0
  image_picker: ^1.0.8
  flutter_calendar_carousel: ^2.4.3
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14

flutter:
  uses-material-design: true